export const SUCCESS_GET_COMMENT_LIST = 'SUCCESS_GET_COMMENT_LIST'; 
export const REQUEST_COMMENT_LIST = 'REQUEST_COMMENT_LIST';
export const REQUEST_COMMENT_CARD = 'REQUEST_COMMENT_CARD';
export const SUCCESS_GET_COMMENT_CARD = 'SUCCESS_GET_COMMENT_CARD';