export const REQUEST_CLIENT_LIST = 'REQUEST_CLIENT_LIST';
export const SUCCESS_GET_CLIENT_LIST = 'SUCCESS_GET_CLIENT_LIST';
export const REQUEST_CLIENT_CARD = 'REQUEST_CLIENT_CARD';
export const SUCCESS_GET_CLIENT_CARD = 'SUCCESS_GET_CLIENT_CARD';